### ISSUE TITLE
Deprecate and archive

### ISSUE THREAD

**Issue by sirreal** [Automattic/react-test-env#12]
This package seems to have limited usage that's being removed and we can archive the repo and deprecate the npm package.

Any problems with that?

@aduth @blowery @gwwar @Tug @ockham @gziolo

**Comment by gziolo** [comment]
Good idea 👍

**Comment by blowery** [comment]
no problems from me

**Comment by sirreal** [comment]
[Deprecated](https://www.npmjs.com/package/react-test-env) and archiving!
