### ISSUE TITLE
Add engines field to package.json to require node >= 4

### ISSUE THREAD

**Issue by ockham** [Automattic/react-test-env#3]
Because of this: https://circleci.com/gh/Automattic/react-test-env/1

(And maybe also a circle.yml?)

cc @Tug @gwwar

**Comment by ockham** [comment]
Heh, @Tug beat me to it: aacc64e7dc753f14034ec16670ca228c21aa4bbb

**Comment by gwwar** [comment]
If you want to force a node test version in circle.yml, the file would look like:

```
machine:
  node:
    version: 5.11.1
```
